### ISSUE TITLE
Wiki: Якщо у вас магато мап :)

### ISSUE THREAD

**Issue by andrewjswan** [J-A-A-M/ukraine_alarm_map#188]
**Опис помилки**
Чіткий і зрозумілий опис помилки.
https://github.com/J-A-A-M/ukraine_alarm_map/wiki/%D0%AF%D0%BA%D1%89%D0%BE-%D1%83-%D0%B2%D0%B0%D1%81-%D0%BC%D0%B0%D0%B3%D0%B0%D1%82%D0%BE-%D0%BC%D0%B0%D0%BF...

Якщо у вас **магато** мап :)

**Comment by v00g100skr** [comment]
дякую))
