### ISSUE TITLE
ПОПЕРЕДЖЕННЯ: бібліотека ESP Async WebServer повинна запускатися на архітектурі 8

### ISSUE THREAD

**Issue by wsitweb** [J-A-A-M/ukraine_alarm_map#206]
При компіляції коду через arduino ide:
ПОПЕРЕДЖЕННЯ: бібліотека ESP Async WebServer повинна запускатися на архітектурі 8 і може бути несумісною з вашою платою на архітектурі esp32.
Після цього низка помилок пов'язані з бібліотеками:

In file included from c:\Users\Admin\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/NeoMethods.h:56,
                 from c:\Users\Admin\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:43,
                 from C:\Users\Admin\Downloads\ukraine_alarm_map-master\src\firmware\firmware.ino:48:
c:\Users\Admin\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/methods/NeoEsp32RmtMethod.h: In destructor 'NeoEsp32RmtMethodBase<T_SPEED, T_CHANNEL>::~NeoEsp32RmtMethodBase()':
c:\Users\Admin\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/methods/NeoEsp32RmtMethod.h:559:9: error: there are no arguments to 'gpio_matrix_out' that depend on a template parameter, so a declaration of 'gpio_matrix_out' must be available [-fpermissive]
  559 |         gpio_matrix_out(_pin, 0x100, false, false);
      |         ^~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/methods/NeoEsp32RmtMethod.h:559:9: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from c:\Users\Admin\Documents\Arduino\libraries\ArduinoWebsockets\src/tiny_websockets/internals/ws_common.hpp:35,
                 from c:\Users\Admin\Documents\Arduino\libraries\ArduinoWebsockets\src/tiny_websockets/message.hpp:3,
                 from c:\Users\Admin\Documents\Arduino\libraries\ArduinoWebsockets\src/ArduinoWebsockets.h:4,
                 from C:\Users\Admin\Downloads\ukraine_alarm_map-master\src\firmware\firmware.ino:57:
c:\Users\Admin\Documents\Arduino\libraries\ArduinoWebsockets\src/tiny_websockets/network/esp32/esp32_tcp.hpp: At global scope:
c:\Users\Admin\Documents\Arduino\libraries\ArduinoWebsockets\src/tiny_websockets/network/esp32/esp32_tcp.hpp:16:60: error: 'WiFiClientSecure' was not declared in this scope; did you mean 'WiFiClient'?
   16 |   class SecuredEsp32TcpClient : public GenericEspTcpClient<WiFiClientSecure> {
      |                                                            ^~~~~~~~~~~~~~~~
      |                                                            WiFiClient
c:\Users\Admin\Documents\Arduino\libraries\ArduinoWebsockets\src/tiny_websockets/network/esp32/esp32_tcp.hpp:16:76: error: template argument 1 is invalid
   16 |   class SecuredEsp32TcpClient : public GenericEspTcpClient<WiFiClientSecure> {
      |                                                                            ^
c:\Users\Admin\Documents\Arduino\libraries\ArduinoWebsockets\src/tiny_websockets/network/esp32/esp32_tcp.hpp: In member function 'void websockets::network::SecuredEsp32TcpClient::setCACert(const char*)':
c:\Users\Admin\Documents\Arduino\libraries\ArduinoWebsockets\src/tiny_websockets/network/esp32/esp32_tcp.hpp:19:13: error: 'class websockets::network::SecuredEsp32TcpClient' has no member named 'client'
   19 |       this->client.setCACert(ca_cert);
      |             ^~~~~~
c:\Users\Admin\Documents\Arduino\libraries\ArduinoWebsockets\src/tiny_websockets/network/esp32/esp32_tcp.hpp: In member function 'void websockets::network::SecuredEsp32TcpClient::setCertificate(const char*)':
c:\Users\Admin\Documents\Arduino\libraries\ArduinoWebsockets\src/tiny_websockets/network/esp32/esp32_tcp.hpp:23:13: error: 'class websockets::network::SecuredEsp32TcpClient' has no member named 'client'
   23 |       this->client.setCertificate(client_ca);
      |             ^~~~~~
c:\Users\Admin\Documents\Arduino\libraries\ArduinoWebsockets\src/tiny_websockets/network/esp32/esp32_tcp.hpp: In member function 'void websockets::network::SecuredEsp32TcpClient::setPrivateKey(const char*)':
c:\Users\Admin\Documents\Arduino\libraries\ArduinoWebsockets\src/tiny_websockets/network/esp32/esp32_tcp.hpp:27:13: error: 'class websockets::network::SecuredEsp32TcpClient' has no member named 'client'
   27 |       this->client.setPrivateKey(private_key);
      |             ^~~~~~
C:\Users\Admin\Downloads\ukraine_alarm_map-master\src\firmware\firmware.ino: In function 'void initHA()':
C:\Users\Admin\Downloads\ukraine_alarm_map-master\src\firmware\firmware.ino:1517:36: error: call of overloaded 'setCurrentState(int&)' is ambiguous
 1517 |       haBrightness->setCurrentState(settings.brightness);
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
In file included from c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/ArduinoHA.h:16,
                 from C:\Users\Admin\Downloads\ukraine_alarm_map-master\src\firmware\firmware.ino:46:
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:16:17: note: candidate: 'void HANumber::setCurrentState(int8_t)'
   16 |     inline void setCurrentState(const type state) \
      |                 ^~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:81:5: note: in expansion of macro '_SET_CURRENT_STATE_OVERLOAD'
   81 |     _SET_CURRENT_STATE_OVERLOAD(int8_t)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:16:17: note: candidate: 'void HANumber::setCurrentState(int16_t)'
   16 |     inline void setCurrentState(const type state) \
      |                 ^~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:82:5: note: in expansion of macro '_SET_CURRENT_STATE_OVERLOAD'
   82 |     _SET_CURRENT_STATE_OVERLOAD(int16_t)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:16:17: note: candidate: 'void HANumber::setCurrentState(int32_t)'
   16 |     inline void setCurrentState(const type state) \
      |                 ^~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:83:5: note: in expansion of macro '_SET_CURRENT_STATE_OVERLOAD'
   83 |     _SET_CURRENT_STATE_OVERLOAD(int32_t)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:16:17: note: candidate: 'void HANumber::setCurrentState(uint8_t)'
   16 |     inline void setCurrentState(const type state) \
      |                 ^~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:84:5: note: in expansion of macro '_SET_CURRENT_STATE_OVERLOAD'
   84 |     _SET_CURRENT_STATE_OVERLOAD(uint8_t)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:16:17: note: candidate: 'void HANumber::setCurrentState(uint16_t)'
   16 |     inline void setCurrentState(const type state) \
      |                 ^~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:85:5: note: in expansion of macro '_SET_CURRENT_STATE_OVERLOAD'
   85 |     _SET_CURRENT_STATE_OVERLOAD(uint16_t)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:16:17: note: candidate: 'void HANumber::setCurrentState(uint32_t)'
   16 |     inline void setCurrentState(const type state) \
      |                 ^~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:86:5: note: in expansion of macro '_SET_CURRENT_STATE_OVERLOAD'
   86 |     _SET_CURRENT_STATE_OVERLOAD(uint32_t)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:16:17: note: candidate: 'void HANumber::setCurrentState(float)'
   16 |     inline void setCurrentState(const type state) \
      |                 ^~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:87:5: note: in expansion of macro '_SET_CURRENT_STATE_OVERLOAD'
   87 |     _SET_CURRENT_STATE_OVERLOAD(float)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\Admin\Downloads\ukraine_alarm_map-master\src\firmware\firmware.ino: In function 'bool saveHaBrightness(int)':
C:\Users\Admin\Downloads\ukraine_alarm_map-master\src\firmware\firmware.ino:2259:27: error: call of overloaded 'setState(int&)' is ambiguous
 2259 |     haBrightness->setState(newBrightness);
      |     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:11:17: note: candidate: 'bool HANumber::setState(int8_t, bool)'
   11 |     inline bool setState(const type state, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:59:5: note: in expansion of macro '_SET_STATE_OVERLOAD'
   59 |     _SET_STATE_OVERLOAD(int8_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:11:17: note: candidate: 'bool HANumber::setState(int16_t, bool)'
   11 |     inline bool setState(const type state, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:60:5: note: in expansion of macro '_SET_STATE_OVERLOAD'
   60 |     _SET_STATE_OVERLOAD(int16_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:11:17: note: candidate: 'bool HANumber::setState(int32_t, bool)'
   11 |     inline bool setState(const type state, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:61:5: note: in expansion of macro '_SET_STATE_OVERLOAD'
   61 |     _SET_STATE_OVERLOAD(int32_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:11:17: note: candidate: 'bool HANumber::setState(uint8_t, bool)'
   11 |     inline bool setState(const type state, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:62:5: note: in expansion of macro '_SET_STATE_OVERLOAD'
   62 |     _SET_STATE_OVERLOAD(uint8_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:11:17: note: candidate: 'bool HANumber::setState(uint16_t, bool)'
   11 |     inline bool setState(const type state, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:63:5: note: in expansion of macro '_SET_STATE_OVERLOAD'
   63 |     _SET_STATE_OVERLOAD(uint16_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:11:17: note: candidate: 'bool HANumber::setState(uint32_t, bool)'
   11 |     inline bool setState(const type state, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:64:5: note: in expansion of macro '_SET_STATE_OVERLOAD'
   64 |     _SET_STATE_OVERLOAD(uint32_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:11:17: note: candidate: 'bool HANumber::setState(float, bool)'
   11 |     inline bool setState(const type state, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HANumber.h:65:5: note: in expansion of macro '_SET_STATE_OVERLOAD'
   65 |     _SET_STATE_OVERLOAD(float)
      |     ^~~~~~~~~~~~~~~~~~~
C:\Users\Admin\Downloads\ukraine_alarm_map-master\src\firmware\firmware.ino: In function 'void uptime()':
C:\Users\Admin\Downloads\ukraine_alarm_map-master\src\firmware\firmware.ino:3960:23: error: call of overloaded 'setValue(int&)' is ambiguous
 3960 |     haUptime->setValue(uptimeValue);
      |     ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
In file included from c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/ArduinoHA.h:20:
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:10:17: note: candidate: 'bool HASensorNumber::setValue(int8_t, bool)'
   10 |     inline bool setValue(const type value, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:47:5: note: in expansion of macro '_SET_VALUE_OVERLOAD'
   47 |     _SET_VALUE_OVERLOAD(int8_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:10:17: note: candidate: 'bool HASensorNumber::setValue(int16_t, bool)'
   10 |     inline bool setValue(const type value, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:48:5: note: in expansion of macro '_SET_VALUE_OVERLOAD'
   48 |     _SET_VALUE_OVERLOAD(int16_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:10:17: note: candidate: 'bool HASensorNumber::setValue(int32_t, bool)'
   10 |     inline bool setValue(const type value, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:49:5: note: in expansion of macro '_SET_VALUE_OVERLOAD'
   49 |     _SET_VALUE_OVERLOAD(int32_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:10:17: note: candidate: 'bool HASensorNumber::setValue(uint8_t, bool)'
   10 |     inline bool setValue(const type value, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:50:5: note: in expansion of macro '_SET_VALUE_OVERLOAD'
   50 |     _SET_VALUE_OVERLOAD(uint8_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:10:17: note: candidate: 'bool HASensorNumber::setValue(uint16_t, bool)'
   10 |     inline bool setValue(const type value, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:51:5: note: in expansion of macro '_SET_VALUE_OVERLOAD'
   51 |     _SET_VALUE_OVERLOAD(uint16_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:10:17: note: candidate: 'bool HASensorNumber::setValue(uint32_t, bool)'
   10 |     inline bool setValue(const type value, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:52:5: note: in expansion of macro '_SET_VALUE_OVERLOAD'
   52 |     _SET_VALUE_OVERLOAD(uint32_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:10:17: note: candidate: 'bool HASensorNumber::setValue(float, bool)'
   10 |     inline bool setValue(const type value, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:53:5: note: in expansion of macro '_SET_VALUE_OVERLOAD'
   53 |     _SET_VALUE_OVERLOAD(float)
      |     ^~~~~~~~~~~~~~~~~~~
C:\Users\Admin\Downloads\ukraine_alarm_map-master\src\firmware\firmware.ino:3961:27: error: call of overloaded 'setValue(int&)' is ambiguous
 3961 |     haWifiSignal->setValue(wifiSignal);
      |     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:10:17: note: candidate: 'bool HASensorNumber::setValue(int8_t, bool)'
   10 |     inline bool setValue(const type value, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:47:5: note: in expansion of macro '_SET_VALUE_OVERLOAD'
   47 |     _SET_VALUE_OVERLOAD(int8_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:10:17: note: candidate: 'bool HASensorNumber::setValue(int16_t, bool)'
   10 |     inline bool setValue(const type value, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:48:5: note: in expansion of macro '_SET_VALUE_OVERLOAD'
   48 |     _SET_VALUE_OVERLOAD(int16_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:10:17: note: candidate: 'bool HASensorNumber::setValue(int32_t, bool)'
   10 |     inline bool setValue(const type value, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:49:5: note: in expansion of macro '_SET_VALUE_OVERLOAD'
   49 |     _SET_VALUE_OVERLOAD(int32_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:10:17: note: candidate: 'bool HASensorNumber::setValue(uint8_t, bool)'
   10 |     inline bool setValue(const type value, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:50:5: note: in expansion of macro '_SET_VALUE_OVERLOAD'
   50 |     _SET_VALUE_OVERLOAD(uint8_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:10:17: note: candidate: 'bool HASensorNumber::setValue(uint16_t, bool)'
   10 |     inline bool setValue(const type value, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:51:5: note: in expansion of macro '_SET_VALUE_OVERLOAD'
   51 |     _SET_VALUE_OVERLOAD(uint16_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:10:17: note: candidate: 'bool HASensorNumber::setValue(uint32_t, bool)'
   10 |     inline bool setValue(const type value, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:52:5: note: in expansion of macro '_SET_VALUE_OVERLOAD'
   52 |     _SET_VALUE_OVERLOAD(uint32_t)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:10:17: note: candidate: 'bool HASensorNumber::setValue(float, bool)'
   10 |     inline bool setValue(const type value, const bool force = false) \
      |                 ^~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\home-assistant-integration\src/device-types/HASensorNumber.h:53:5: note: in expansion of macro '_SET_VALUE_OVERLOAD'
   53 |     _SET_VALUE_OVERLOAD(float)
      |     ^~~~~~~~~~~~~~~~~~~
c:\Users\Admin\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/methods/NeoEsp32RmtMethod.h: In instantiation of 'NeoEsp32RmtMethodBase<T_SPEED, T_CHANNEL>::~NeoEsp32RmtMethodBase() [with T_SPEED = NeoEsp32RmtSpeedWs2812x; T_CHANNEL = NeoEsp32RmtChannel1]':
c:\Users\Admin\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:55:9:   required from 'NeoPixelBus<T_COLOR_FEATURE, T_METHOD>::NeoPixelBus(uint16_t, uint8_t) [with T_COLOR_FEATURE = NeoGrbFeature; T_METHOD = NeoEsp32RmtMethodBase<NeoEsp32RmtSpeedWs2812x, NeoEsp32RmtChannel1>; uint16_t = short unsigned int; uint8_t = unsigned char]'
C:\Users\Admin\Downloads\ukraine_alarm_map-master\src\firmware\firmware.ino:1174:98:   required from here
c:\Users\Admin\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/methods/NeoEsp32RmtMethod.h:559:24: error: 'gpio_matrix_out' was not declared in this scope; did you mean 'gpio_iomux_out'?
  559 |         gpio_matrix_out(_pin, 0x100, false, false);
      |         ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         gpio_iomux_out

exit status 1

Compilation error: call of overloaded 'setCurrentState(int&)' is ambiguous

**Comment by v00g100skr** [comment]
яка плата у вас фізично? 
яка версія board manager? має бути 2.0.14
яка назва плати вибрана для компіляції?

**Comment by v00g100skr** [comment]
поки що виглядає, що це нестандартна плата по типу C3, наприклад, яка не підтримується деякими лібами на рівні коду цих ліб
