### ISSUE TITLE
Вiдображення ракет перестали працювати

### ISSUE THREAD

**Issue by chertvl** [J-A-A-M/ukraine_alarm_map#210]
**Опис помилки**
Вiдображення ракет з сервiсу начебто не вiдбуваються вже пару мiсяцiв.
За посиланням на api видно, що останнi оновлення були дуже давно.
Не можу знати данi перестали йти з сервiсу eTryvoga або помилка з кешем на нашому ресурсi.

**Comment by andrewjswan** [comment]
> А звідки у вас це посилання?

Ми стежимо за розвитком проекту. :)

**Comment by v00g100skr** [comment]
пофікшено
